language: c

branches:
  only:
    - master

sudo: required
dist: trusty
matrix:
  include:
    - os: linux

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - DEBUG=true
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "8756 C4F7 65C9 AC3C B6B8  5D62 379C E192 D401 AB61"
  - echo "deb https://dl.bintray.com/pony-language/ponyc-debian pony-language main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -V install ponyc

script:
  - free -h
  - make test && /usr/bin/time -v ./test --exclude="(fail)"
  - make examples
